- name: Install Ruby
  hosts: all
  become: true
  tasks:
  - name: Update repositories cache and install packages
    apt:
      pkg:
      - ruby-full
      - ruby-bundler
      - build-essential
      update_cache: yes
