- name: Install MongoDB
  hosts: all
  become: true
  tasks:
  - name: Update repositories cache and install package
    apt:
      pkg: mongodb
      update_cache: yes
  - name: Enable MongoDB service
    systemd:
      name: mongodb
      enabled: yes
